# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: quantum_engine.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'quantum_engine.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14quantum_engine.proto\x12\rqtwin.physics\"m\n\tQubitSpec\x12\x10\n\x08qubit_id\x18\x01 \x01(\r\x12\x15\n\rfrequency_ghz\x18\x02 \x01(\x01\x12\x19\n\x11\x61nharmonicity_mhz\x18\x03 \x01(\x01\x12\r\n\x05t1_us\x18\x04 \x01(\x01\x12\r\n\x05t2_us\x18\x05 \x01(\x01\"\x90\x01\n\x13SystemParamsRequest\x12\x12\n\nnum_qubits\x18\x01 \x01(\r\x12(\n\x06qubits\x18\x02 \x03(\x0b\x32\x18.qtwin.physics.QubitSpec\x12\x19\n\x11\x63oupling_matrix_j\x18\x03 \x03(\x01\x12 \n\x18\x63ontrol_crosstalk_matrix\x18\x04 \x03(\x01\"L\n\x0e\x43ontrolSignals\x12\x10\n\x08qubit_id\x18\x01 \x01(\r\x12\x13\n\x0bi_amplitude\x18\x02 \x01(\x01\x12\x13\n\x0bq_amplitude\x18\x03 \x01(\x01\"\x8b\x01\n\x11SimulationRequest\x12\x12\n\ndelta_t_ns\x18\x01 \x01(\x01\x12\x16\n\x0etemperature_mk\x18\x02 \x01(\x01\x12\x14\n\x0cpressure_mpa\x18\x03 \x01(\x01\x12\x34\n\rdrive_signals\x18\x04 \x03(\x0b\x32\x1d.qtwin.physics.ControlSignals\"\x9d\x01\n\x12SimulationResponse\x12\x1b\n\x13\x64\x65nsity_matrix_real\x18\x01 \x03(\x01\x12\x1b\n\x13\x64\x65nsity_matrix_imag\x18\x02 \x03(\x01\x12\x14\n\x0ctensor_shape\x18\x03 \x03(\r\x12\x18\n\x10\x61verage_fidelity\x18\x04 \x01(\x01\x12\x1d\n\x15total_crosstalk_error\x18\x05 \x01(\x01\"Y\n\x14SystemParamsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x1f\n\x17hilbert_space_dimension\x18\x03 \x01(\x04\x32\xc3\x01\n\rQuantumEngine\x12S\n\x0cSimulateStep\x12 .qtwin.physics.SimulationRequest\x1a!.qtwin.physics.SimulationResponse\x12]\n\x12UpdateSystemParams\x12\".qtwin.physics.SystemParamsRequest\x1a#.qtwin.physics.SystemParamsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'quantum_engine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUBITSPEC']._serialized_start=39
  _globals['_QUBITSPEC']._serialized_end=148
  _globals['_SYSTEMPARAMSREQUEST']._serialized_start=151
  _globals['_SYSTEMPARAMSREQUEST']._serialized_end=295
  _globals['_CONTROLSIGNALS']._serialized_start=297
  _globals['_CONTROLSIGNALS']._serialized_end=373
  _globals['_SIMULATIONREQUEST']._serialized_start=376
  _globals['_SIMULATIONREQUEST']._serialized_end=515
  _globals['_SIMULATIONRESPONSE']._serialized_start=518
  _globals['_SIMULATIONRESPONSE']._serialized_end=675
  _globals['_SYSTEMPARAMSRESPONSE']._serialized_start=677
  _globals['_SYSTEMPARAMSRESPONSE']._serialized_end=766
  _globals['_QUANTUMENGINE']._serialized_start=769
  _globals['_QUANTUMENGINE']._serialized_end=964
# @@protoc_insertion_point(module_scope)
